### ISSUE TITLE
spiders in your tribble

### ISSUE THREAD

**Issue by pvanzand** [matt-dray/tidyswirl#15]
I struggled with answering the question about using tribble() for the legs_tbl because the instructions ask for this:

| Use the tribble() function to recreate your earlier tibble. The column headers should
| be 'animal' and 'legs' with rows for 'cat', 'snake' and 'spider'.

but the code you were looking for was:

tribble(~animal, ~legs, "cat", 4, "snake", 0, "bird", 2)

**Comment by matt-dray** [comment]
Thank you very much for spotting this @pvanzand. Spiders appear later in the lesson of course; I must have forgotten to change the wording. I cleaned up the problem along with the fix for #14. 

I recommend uninstalling the old version of tidyswirl and then installing the updated version like this:

``` r
swirl::uninstall_course("tidyswirl")  # uninstall old version of the course
swirl::install_course_github("matt-dray", "tidyswirl")  # install new version
```
