### ISSUE TITLE
typo in the hint for airquality_tbl<- as_tibble(airquality)

### ISSUE THREAD

**Issue by MT-Lange** [matt-dray/tidyswirl#16]
after entering a wrong answer, the hint calls the object "airquality_tbla", with an extra "a". 
It caused me a bit of confusion.

**Comment by matt-dray** [comment]
Good spot @Natacorb, thank you. I've now fixed this. I recommend you uninstall and reinstall the course if you want to use it again, like this:

``` r
swirl::uninstall_course("tidyswirl")  # uninstall old version of the course
swirl::install_course_github("matt-dray", "tidyswirl")  # install new version
```

**Comment by MT-Lange** [comment]
thank you for your courses!. They are immensly helpful in understanding R and stop hating it too much.
