### ISSUE TITLE
Tibble question answer error

### ISSUE THREAD

**Issue by catatk** [matt-dray/tidyswirl#8]
Loving the tidyswirl exercises. There seems to be an error in the answers to "Compare the data.frame output to the tibble output. Which of the following is true?".  The possible answers are:
1: Tibbles give the data type of each column
2: Tibbles use colour to provide meaning
3: Tibbles print fewer rows
4: All of these are true
I think 4 should be correct but that is not being accepted as the correct answer.

**Comment by matt-dray** [comment]
Thank you @catatk for pointing out the error. This is now fixed. The problem was that 'All of these are true' was presented as an answer, but the underlying test mechanism was coded as 'All of the above'.
